export const carfilterData = [
  {
    key: "brands",
    name: "Car Brand",
    type: "checkbox",
    values: [
      { label: "Tesla", value: "Tesla" },
      { label: "Ford", value: "Ford" },
      { label: "Mercedes Benz", value: "Mercedes Benz" },
      { label: "Audi", value: "Audi" },
      { label: "Kia", value: "Kia" },
      { label: "Honda", value: "Honda" },
      { label: "Toyota", value: "Toyota" },
    ],
  },
  {
    key: "categories",
    name: "Car Category",
    type: "checkbox",
    values: [
      { label: "Sedan", value: "Sedan" },
      { label: "Hatchback", value: "Hatchback" },
      { label: "SUV", value: "SUV" },
      { label: "Coupes", value: "Coupes" },
    ],
  },
  {
    key: "years",
    name: "Year",
    type: "checkbox",
    values: [
      { label: "2025", value: 2025 },
      { label: "2024", value: 2024 },
      { label: "2023", value: 2023 },
      { label: "2022", value: 2022 },
      { label: "2021", value: 2021 },
      { label: "2020", value: 2020 },
      { label: "2019", value: 2019 },
      { label: "2018", value: 2018 },
      { label: "2017", value: 2017 },
      { label: "2016", value: 2016 },
    ],
  },
  {
    key: "fuelType",
    name: "Fuel Type",
    type: "radio",
    values: [
      { label: "Petrol", value: "Petrol" },
      { label: "Diesel", value: "Diesel" },
      { label: "Electric", value: "Electric" },
      { label: "CNG", value: "CNG" },
      { label: "Hybrid", value: "Hybrid" },
    ],
  },
  {
    key: "specifications",
    name: "Car Specifications",
    type: "checkbox",
    values: [
      { label: "Air Condition", value: "Air Condition" },
      { label: "Climate Control", value: "Climate Control" },
      { label: "Luxury Climate Control", value: "Luxury Climate Control" },
      { label: "Sunroof", value: "Sunroof" },
      { label: "Push-button Start", value: "Push-button Start" },
      { label: "Parking Sensors", value: "Parking Sensors" },
      { label: "Bluetooth", value: "Bluetooth" },
      { label: "Usb", value: "Usb" },
      { label: "Cruise Control", value: "Cruise Control" },
      { label: "Android Auto", value: "Android Auto" },
      { label: "360-degree Camera", value: "360-degree Camera" },
    ],
  },
  {
    key: "seating",
    name: "Capacity",
    type: "checkbox",
    values: [
      { label: "2 Seater", value: 2 },
      { label: "4 Seater", value: 4 },
      { label: "5 Seater", value: 5 },
      { label: "7 Seater", value: 7 },
    ],
  },
  {
    key: "transmission",
    name: "Transmission",
    type: "radio",
    values: [
      { label: "Manual", value: "Manual" },
      { label: "Semi-Automatic", value: "Semi-Automatic" },
      { label: "Automatic", value: "Automatic" },
    ],
  },
];