export const carsData = [
  {
    key: "1",
    IMAGE: "car-01.jpg",
    CAR: "Ford Endeavour",
    CAR_TYPE: "Sedan",
    BASE_LOCATION: "Newyork City",
    PRICE: "₹3500",
    DAMAGES: "01",
    IS_FEATURED: "",
    CREATED_DATE: "25 May 2025",
    STATUS: "Active",
  },
  {
    key: "2",
    IMAGE: "car-02.jpg",
    CAR: "Ferrari 458 MM",
    CAR_TYPE: "Convertible",
    BASE_LOCATION: "Los Angeles",
    PRICE: "₹2800",
    DAMAGES: "05",
    IS_FEATURED: "",
    CREATED_DATE: "25 May 2025",
    STATUS: "Inactive",
  },
  {
    key: "3",
    IMAGE: "car-03.jpg",
    CAR: "Ford Mustang ",
    CAR_TYPE: "Coupe",
    BASE_LOCATION: "Chicago",
    PRICE: "₹1425",
    DAMAGES: "05",
    IS_FEATURED: "",
    CREATED_DATE: "25 May 2025",
    STATUS: "Active",
  },
  {
    key: "4",
    IMAGE: "car-04.jpg",
    CAR: "Toyota Tacoma 4",
    CAR_TYPE: "Hatchback",
    BASE_LOCATION: "Houston",
    PRICE: "₹745",
    DAMAGES: "04",
    IS_FEATURED: "",
    CREATED_DATE: "25 May 2025",
    STATUS: "Active",
  },
  {
    key: "5",
    IMAGE: "car-05.jpg",
    CAR: "Chevrolet Pick",
    CAR_TYPE: "Sedan",
    BASE_LOCATION: "Phoenix",
    PRICE: "₹659",
    DAMAGES: "02",
    IS_FEATURED: "",
    CREATED_DATE: "25 May 2025",
    STATUS: "Active",
  },
  {
    key: "6",
    IMAGE: "car-06.jpg",
    CAR: "Etios Carmen",
    CAR_TYPE: "Hatchback",
    BASE_LOCATION: "Philadelphia",
    PRICE: "₹254",
    DAMAGES: "01",
    IS_FEATURED: "",
    CREATED_DATE: "25 May 2025",
    STATUS: "Active",
  },
  {
    key: "7",
    IMAGE: "car-07.jpg",
    CAR: "Acura Sport Version",
    CAR_TYPE: "Crossover",
    BASE_LOCATION: "Austin",
    PRICE: "₹1240",
    DAMAGES: "05",
    IS_FEATURED: "",
    CREATED_DATE: "25 May 2025",
    STATUS: "Active",
  },
  {
    key: "8",
    IMAGE: "car-08.jpg",
    CAR: "Kia Soul 2016 Station",
    CAR_TYPE: "Wagon",
    BASE_LOCATION: "San Antonio",
    PRICE: "₹1425",
    DAMAGES: "02",
    IS_FEATURED: "",
    CREATED_DATE: "25 May 2025",
    STATUS: "Active",
  },
  {
    key: "9",
    IMAGE: "car-11.jpg",
    CAR: "Chevrolet Camaro Station",
    CAR_TYPE: "Wagon",
    BASE_LOCATION: "Los Angeles",
    PRICE: "₹4124",
    DAMAGES: "03",
    IS_FEATURED: "",
    CREATED_DATE: "25 May 2025",
    STATUS: "Inactive",
  },
  {
    key: "10",
    IMAGE: "car-10.jpg",
    CAR: "Toyota Camry SE 350 Mini Van",
    CAR_TYPE: "Mini Van",
    BASE_LOCATION: "Chicago",
    PRICE: "₹4741",
    DAMAGES: "02",
    IS_FEATURED: "",
    CREATED_DATE: "25 May 2025",
    STATUS: "Active",
  },
];
