export const modelsData = [
    {
      key: "1",
      MODEL: "Urban Cruiser",
      BRAND: "Toyota",
      TOTALCARS: "10",
      STATUS: "Active",
    },
    {
      key: "2",
      MODEL: "Fortuner",
      BRAND: "Toyota",
      TOTALCARS: "10",
      STATUS: "Inactive",
    },
    {
      key: "3",
      MODEL: "V8",
      BRAND: "Audi",
      TOTALCARS: "25",
      STATUS: "Active",
    },
    {
      key: "4",
      MODEL: "Q3",
      BRAND: "Audi",
      TOTALCARS: "15",
      STATUS: "Active",
    },
    {
      key: "5",
      MODEL: "Huracan",
      BRAND: "Lamborghini",
      TOTALCARS: "5",
      STATUS: "Inactive",
    },
    {
      key: "6",
      MODEL: "Sian",
      BRAND: "Lamborghini",
      TOTALCARS: "35",
      STATUS: "Inactive",
    },
    {
      key: "7",
      MODEL: "X5",
      BRAND: "BMW",
      TOTALCARS: "20",
      STATUS: "Active",
    },
    {
      key: "8",
      MODEL: "XM",
      BRAND: "BMW",
      TOTALCARS: "32",
      STATUS: "Active",
    },
    {
      key: "9",
      MODEL: "Sonet",
      BRAND: "KIA",
      TOTALCARS: "20",
      STATUS: "Active",
    },
    {
      key: "10",
      MODEL: "Seltos",
      BRAND: "KIA",
      TOTALCARS: "20",
      STATUS: "Active",
    },
]