export const brandsData = [
    {
      key: "1",
      NAME: "Toyota",
      IMAGE: "toyota.svg",
      TOTALCARS: "20",
      STATUS: "Active",
    },
    {
      key: "2",
      NAME: "Audi",
      IMAGE: "audi.svg",
      TOTALCARS: "15",
      STATUS: "Inactive",
    },
    {
      key: "3",
      NAME: "Lamborghini",
      IMAGE: "lamborghini.svg",
      TOTALCARS: "45",
      STATUS: "Active",
    },
    {
      key: "4",
      NAME: "BMW",
      IMAGE: "bmw.svg",
      TOTALCARS: "30",
      STATUS: "Active",
    },
    {
      key: "5",
      NAME: "Ferrari",
      IMAGE: "ferrari.svg",
      TOTALCARS: "45",
      STATUS: "Inactive",
    },
    {
      key: "6",
      NAME: "Honda",
      IMAGE: "toyota.svg",
      TOTALCARS: "20",
      STATUS: "Active",
    },
    {
      key: "7",
      NAME: "Ford",
      IMAGE: "honda.svg",
      TOTALCARS: "22",
      STATUS: "Active",
    },
    {
      key: "8",
      NAME: "KIA",
      IMAGE: "ford.svg",
      TOTALCARS: "22",
      STATUS: "Active",
    },
    {
      key: "9",
      NAME: "Hyundai",
      IMAGE: "kia-new.svg",
      TOTALCARS: "32",
      STATUS: "Active",
    },
    {
      key: "10",
      NAME: "Mercedes-Benz",
      IMAGE: "hyundai.svg",
      TOTALCARS: "40",
      STATUS: "Active",
    },
]