export const LocationData = [
  {
    key: "1",
    IMAGE: "location-01.jpg",
    LOCATION_TITLE: "Johnson Dealer Zone",
    ADDRESS: "2881 Jarvis Street",
    PHONE: "+1 56598 98956",
    WORKING_DAYS: [
      { id: 1, DAYS: "M", active: true },
      { id: 2, DAYS: "T", active: false },
      { id: 3, DAYS: "W", active: true },
      { id: 4, DAYS: "T", active: false },
      { id: 5, DAYS: "F", active: true },
      { id: 6, DAYS: "S", active: true },
      { id: 7, DAYS: "S", active: false },
    ],
    STATUS: "Enabled",
  },
  {
    key: "2",
    IMAGE: "location-02.jpg",
    LOCATION_TITLE: "Miller Auto Trade Zone",
    ADDRESS: "354 Java Lane",
    PHONE: "+1 24558 56599",
    WORKING_DAYS: [
      { id: 1, DAYS: "M", active: true },
      { id: 2, DAYS: "T", active: true },
      { id: 3, DAYS: "W", active: true },
      { id: 4, DAYS: "T", active: false },
      { id: 5, DAYS: "F", active: false },
      { id: 6, DAYS: "S", active: false },
      { id: 7, DAYS: "S", active: true },
    ],
    STATUS: "Disabled",
  },
  {
    key: "3",
    IMAGE: "location-03.jpg",
    LOCATION_TITLE: "Thompson Dealer Parking",
    ADDRESS: "849 Circle Drive",
    PHONE: "+1 25669 88985",
    WORKING_DAYS: [
      { id: 1, DAYS: "M", active: true },
      { id: 2, DAYS: "T", active: true },
      { id: 3, DAYS: "W", active: false },
      { id: 4, DAYS: "T", active: true },
      { id: 5, DAYS: "F", active: true },
      { id: 6, DAYS: "S", active: false },
      { id: 7, DAYS: "S", active: false },
    ],
    STATUS: "Enabled",
  },
  {
    key: "4",
    IMAGE: "location-04.jpg",
    LOCATION_TITLE: "Smith Auto Dealer Lot",
    ADDRESS: "239 Clousson Road",
    PHONE: "+1 54698 55468",
    WORKING_DAYS: [
      { id: 1, DAYS: "M", active: true },
      { id: 2, DAYS: "T", active: true },
      { id: 3, DAYS: "W", active: false },
      { id: 4, DAYS: "T", active: false },
      { id: 5, DAYS: "F", active: false },
      { id: 6, DAYS: "S", active: false },
      { id: 7, DAYS: "S", active: true },
    ],
    STATUS: "Enabled",
  },
  {
    key: "5",
    IMAGE: "location-05.jpg",
    LOCATION_TITLE: "Anderson Dealer Zone",
    ADDRESS: "728 Glenview Drive",
    PHONE: "+1 32569 15458",
    WORKING_DAYS: [
      { id: 1, DAYS: "M", active: true },
      { id: 2, DAYS: "T", active: false },
      { id: 3, DAYS: "W", active: true },
      { id: 4, DAYS: "T", active: true },
      { id: 5, DAYS: "F", active: true },
      { id: 6, DAYS: "S", active: false },
      { id: 7, DAYS: "S", active: false },
    ],
    STATUS: "Enabled",
  },
  {
    key: "6",
    IMAGE: "location-06.jpg",
    LOCATION_TITLE: "Carter Dealer Holding Lot",
    ADDRESS: "39 Blackwell Street",
    PHONE: "+1 65895 47878",
    WORKING_DAYS: [
      { id: 1, DAYS: "M", active: true },
      { id: 2, DAYS: "T", active: false },
      { id: 3, DAYS: "W", active: true },
      { id: 4, DAYS: "T", active: false },
      { id: 5, DAYS: "F", active: true },
      { id: 6, DAYS: "S", active: false },
      { id: 7, DAYS: "S", active: true },
    ],
    STATUS: "Enabled",
  },
  {
    key: "7",
    IMAGE: "location-07.jpg",
    LOCATION_TITLE: "Walker Auto Trade Yard",
    ADDRESS: "75 Cambridge Place",
    PHONE: "+1 14782 14578",
    WORKING_DAYS: [
      { id: 1, DAYS: "M", active: true },
      { id: 2, DAYS: "T", active: false },
      { id: 3, DAYS: "W", active: false },
      { id: 4, DAYS: "T", active: true },
      { id: 5, DAYS: "F", active: true },
      { id: 6, DAYS: "S", active: false },
      { id: 7, DAYS: "S", active: false },
    ],
    STATUS: "Enabled",
  },
  {
    key: "8",
    IMAGE: "location-08.jpg",
    LOCATION_TITLE: "Taylor Auto Dealer Zone",
    ADDRESS: "56 Garfield Road",
    PHONE: "+1 12488 14457",
    WORKING_DAYS: [
      { id: 1, DAYS: "M", active: false },
      { id: 2, DAYS: "T", active: true },
      { id: 3, DAYS: "W", active: true },
      { id: 4, DAYS: "T", active: true },
      { id: 5, DAYS: "F", active: false },
      { id: 6, DAYS: "S", active: true },
      { id: 7, DAYS: "S", active: false },
    ],
    STATUS: "Enabled",
  },
  {
    key: "9",
    IMAGE: "location-09.jpg",
    LOCATION_TITLE: "Evans Dealer Car Zone",
    ADDRESS: "2042 Strother Street",
    PHONE: "+1 12781 02567",
    WORKING_DAYS: [
      { id: 1, DAYS: "M", active: true },
      { id: 2, DAYS: "T", active: true },
      { id: 3, DAYS: "W", active: true },
      { id: 4, DAYS: "T", active: true },
      { id: 5, DAYS: "F", active: true },
      { id: 6, DAYS: "S", active: false },
      { id: 7, DAYS: "S", active: false },
    ],
    STATUS: "Disabled",
  },
  {
    key: "10",
    IMAGE: "location-10.jpg",
    LOCATION_TITLE: "Allen Dealer Parking Lot",
    ADDRESS: "743 Simpson Square",
    PHONE: "+1 12124 1425556",
    WORKING_DAYS: [
      { id: 1, DAYS: "M", active: true },
      { id: 2, DAYS: "T", active: true },
      { id: 3, DAYS: "W", active: true },
      { id: 4, DAYS: "T", active: true },
      { id: 5, DAYS: "F", active: false },
      { id: 6, DAYS: "S", active: false },
      { id: 7, DAYS: "S", active: true },
    ],
    STATUS: "Enabled",
  },
];
